#!/bin/bash
################################################################################
# Backlog Management Module
# Purpose: Workflow summary and backlog report generation
# Part of: Tests & Documentation Workflow Automation v2.0.0
################################################################################

# ==============================================================================
# WORKFLOW SUMMARY GENERATION
# ==============================================================================

# Create a comprehensive summary file for the entire workflow run
# Called at the end of execute_full_workflow()
create_workflow_summary() {
    local summary_file="${BACKLOG_RUN_DIR}/WORKFLOW_SUMMARY.md"
    
    if [[ "$DRY_RUN" == true ]]; then
        print_info "[DRY RUN] Would create workflow summary: $summary_file"
        return 0
    fi
    
    cat > "$summary_file" << EOF
# Workflow Execution Summary

**Workflow Run ID:** ${WORKFLOW_RUN_ID}
**Execution Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Script Version:** ${SCRIPT_VERSION}
**Mode:** $([ "$AUTO_MODE" = true ] && echo "Automatic" || echo "Interactive")

---

## Execution Overview

### Steps Completed

EOF
    
    # Add step status for each of the 13 steps (0-11 + step numbering)
    local step_num=0
    for step_num in {0..11}; do
        local step_key="step${step_num}"
        local step_status="${WORKFLOW_STATUS[$step_key]:-⏭️}"
        echo "- **Step ${step_num}:** ${step_status}" >> "$summary_file"
    done
    
    cat >> "$summary_file" << EOF

### Change Analysis

- **Change Scope:** ${CHANGE_SCOPE:-Not specified}
- **Commits Ahead:** ${ANALYSIS_COMMITS:-0}
- **Modified Files:** ${ANALYSIS_MODIFIED:-0}

---

## Individual Step Reports

EOF
    
    # List all step reports in this run
    for step_file in "$BACKLOG_RUN_DIR"/step*.md; do
        if [[ -f "$step_file" ]]; then
            local step_name
            step_name=$(basename "$step_file" .md)
            echo "- [\`${step_name}\`](./${step_name}.md)" >> "$summary_file"
        fi
    done
    
    cat >> "$summary_file" << EOF

---

## How to Use These Reports

1. **Review Individual Steps:** Click on any step report above to see detailed findings
2. **Address Issues:** Work through issues by priority (Critical → High → Medium → Low)
3. **Track Progress:** Mark issues as resolved and update documentation
4. **Archive:** Move resolved workflow runs to \`shell_scripts/workflow/backlog/archive/\` for historical reference

---

**Generated by:** ${SCRIPT_NAME} v${SCRIPT_VERSION}
EOF
    
    print_success "Workflow summary created: $summary_file"
}

# Export backlog functions
export -f create_workflow_summary
