#!/bin/bash
################################################################################
# Utility Functions Module
# Purpose: Common utility functions for workflow automation
# Part of: Tests & Documentation Workflow Automation v2.0.0
################################################################################

# ==============================================================================
# PRINT FUNCTIONS - Formatted console output with colors
# ==============================================================================

print_header() {
    local message="$1"
    echo -e "\n${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  ${message}${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}\n"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ ERROR: $1${NC}" >&2
}

print_warning() {
    echo -e "${YELLOW}⚠️  WARNING: $1${NC}"
}

print_info() {
    echo -e "${CYAN}ℹ️  $1${NC}"
}

print_step() {
    local step_num="$1"
    local step_name="$2"
    echo -e "\n${MAGENTA}▶ Step ${step_num}: ${step_name}${NC}"
}

# ==============================================================================
# BACKLOG AND SUMMARY HELPERS
# ==============================================================================

# Save issues found in a step to backlog
# Usage: save_step_issues <step_num> <step_name> <issues_content>
save_step_issues() {
    local step_num="$1"
    local step_name="$2"
    local issues_content="$3"
    
    if [[ "$DRY_RUN" == true ]]; then
        return 0
    fi
    
    # Create backlog directory structure if it doesn't exist
    mkdir -p "$BACKLOG_RUN_DIR"
    
    local step_file="${BACKLOG_RUN_DIR}/step${step_num}_${step_name// /_}.md"
    
    # Process content to convert \n to actual newlines
    local processed_content=$(echo -e "${issues_content}")
    
    # Create markdown report
    cat > "$step_file" << EOF
# Step ${step_num}: ${step_name}

**Workflow Run ID:** ${WORKFLOW_RUN_ID}
**Timestamp:** $(date '+%Y-%m-%d %H:%M:%S')
**Status:** Issues Found

---

## Issues and Findings

${processed_content}

---

**Generated by:** ${SCRIPT_NAME} v${SCRIPT_VERSION}
EOF
    
    print_info "Saved issues to: ${step_file}"
}

# Save step conclusion summary to summaries folder
# Usage: save_step_summary <step_num> <step_name> <summary_content> <status>
save_step_summary() {
    local step_num="$1"
    local step_name="$2"
    local summary_content="$3"
    local status="${4:-✅}"
    
    if [[ "$DRY_RUN" == true ]]; then
        return 0
    fi
    
    # Create summaries directory structure if it doesn't exist
    mkdir -p "$SUMMARIES_RUN_DIR"
    
    local summary_file="${SUMMARIES_RUN_DIR}/step${step_num}_${step_name// /_}_summary.md"
    
    # Create concise summary report
    cat > "$summary_file" << EOF
# Step ${step_num}: ${step_name} - Summary

**Status:** ${status}
**Timestamp:** $(date '+%Y-%m-%d %H:%M:%S')
**Workflow Run:** ${WORKFLOW_RUN_ID}

---

## Conclusion

${summary_content}

---

*Generated by ${SCRIPT_NAME} v${SCRIPT_VERSION}*
EOF
    
    print_info "Saved summary to: ${summary_file}"
}

# ==============================================================================
# USER INTERACTION
# ==============================================================================

# User confirmation prompt with auto-mode bypass
# Usage: confirm_action <prompt> [default_answer]
# Returns: 0 for yes, 1 for no
confirm_action() {
    local prompt="$1"
    local default_answer="${2:-}"  # Optional: "y", "n", or empty
    local response
    local prompt_suffix
    
    # Auto mode always returns true (yes)
    if [[ "$AUTO_MODE" == true ]]; then
        return 0
    fi
    
    # Build prompt suffix based on default answer
    if [[ "$default_answer" == "y" ]]; then
        prompt_suffix=" (Y/n): "
    elif [[ "$default_answer" == "n" ]]; then
        prompt_suffix=" (y/N): "
    else
        prompt_suffix=" (y/n): "
    fi
    
    read -p "$(echo -e "${YELLOW}${prompt}${prompt_suffix}${NC}")" response
    
    # Handle empty response with default answer
    if [[ -z "$response" && -n "$default_answer" ]]; then
        response="$default_answer"
    fi
    
    [[ "$response" =~ ^[Yy]$ ]]
}

# ==============================================================================
# CLEANUP AND RESOURCE MANAGEMENT
# ==============================================================================

# Cleanup handler for temporary files
# Registered via trap in main() to ensure cleanup on EXIT/INT/TERM
cleanup() {
    if [[ ${#TEMP_FILES[@]} -gt 0 ]]; then
        print_info "Cleaning up temporary files..."
        for temp_file in "${TEMP_FILES[@]}"; do
            [[ -f "$temp_file" ]] && rm -f "$temp_file"
        done
    fi
}

# ==============================================================================
# WORKFLOW PROGRESS TRACKING
# ==============================================================================

# Update workflow status for a step
# Usage: update_workflow_status <step_name> <status>
update_workflow_status() {
    local step="$1"
    local status="$2"
    WORKFLOW_STATUS["$step"]="$status"
}

# Show overall workflow progress
show_progress() {
    local completed=0
    for status in "${WORKFLOW_STATUS[@]}"; do
        [[ "$status" == "✅" ]] && ((completed++))
    done
    
    echo -e "\n${CYAN}Progress: ${completed}/${TOTAL_STEPS} steps completed${NC}"
}

# Export all utility functions
export -f print_header print_success print_error print_warning print_info print_step
export -f save_step_issues save_step_summary
export -f confirm_action cleanup
export -f update_workflow_status show_progress
